name: Go
on: [push, pull_request]
jobs:

  test:
    strategy:
      matrix:
        go-version: [1.20.x, 1.21.x, 1.22.x, 1.23.x, 1.24.x]
        os: [ubuntu-24.04, macos-latest]
        targetplatform: [x86, x64]

    runs-on: ${{ matrix.os }}

    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: false
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v -race -coverprofile='coverage.txt' -covermode=atomic ./...

    - name: Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: coverage.txt
        flags: unittests
        name: codecov-umbrella
